-- ─── 004: Superseded by 005_canonical_schema.sql ───
-- This migration previously dropped make_public. That is now handled
-- non-destructively in 005 (RENAME to _make_public_legacy).
-- Kept as a no-op so migration numbering stays consistent.
-- No action needed.
